module.exports = {
  'likes':             "{likes, number} me gusta",
  'home':              'Inicio',
  'my-profile':        'Perfil',
  'logout':            'Salir',
  'login':             'Iniciar sesión',
  'language':          'Idioma',
  'english':           'Inglés',
  'spanish':           'Español',
  'signup.subheading': 'Registrate para ver fotos de tus amigos estudiando duro',
  'signin.facebook':   'Iniciar sesión con ',
  'email':             'Correo electrónico',
  'username':          'Nombre de usuario',
  'fullname':          'Nombre completo',
  'password':          'Contraseña',
  'signup.action':     'Registrate',
  'signup.account':    '¿Tienes una cuenta?',
  'signin':            'Iniciar sesión',
  'signup':            'Registrarse',
  'signin.account':    '¿No tienes una cuenta?',
  'language':          'Idioma',
  'upload-picture':       'Subir foto',
  'upload':            '¡Subir!',
  'cancel':            'Cancelar'
}
